---
abstract: 'A JSON based config file system.'
author:
  - 'JT Smith <RIZEN@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102340, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-JSON
requires:
  Any::Moose: 0.13
  File::Temp: 0.18
  JSON: 2.16
  List::Util: 1.19
  Test::Deep: 0.095
  Test::More: 0.7
version: 1.5100
